// Generated by LiveScript 1.3.1
(function(){
  var s;
  s = skrollr.init({
    forceHeight: false
  });
  skrollr.menu.init(s, {
    animate: true,
    easing: 'sqrt',
    duration: function(currentTop, targetTop){
      return 300;
    }
  });
}).call(this);
