// Generated by LiveScript 1.2.0
(function(){
  angular.module('SELab', ['duScroll']).controller('PageController', function($scope, $document){
    return console.log('start!!');
  }).controller('AboutController', function($scope){
    $scope.about_info = [{
      address: '台南市 東區 大學路1號 國立成功大學 成功校區 資訊系新館65912室',
      email: 'selab@mail.csie.ncku.edu.tw',
      tel: '+886-6-2757575　ext 62520　ext 2912'
    }];
    return console.log('about');
  });
}).call(this);
